a = input('digite algo: ')
print('O tipo primitivo desse valor é', type (a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético', a.isalpha())
print('Está em minusculas?', a.islower())
print('Está capitalizada? ', a.istitle())