num = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print ('{} x {} = {}'.format(num, 1, num*1))
print ('{} x {} = {}'.format(num, 2, num*2))
print ('{} x {} = {}'.format(num, 3, num*2))
print ('{} x {} = {}'.format(num, 4, num*2))
print ('{} x {} = {}'.format(num, 5, num*2))
print ('{} x {} = {}'.format(num, 6, num*2))
print ('{} x {} = {}'.format(num, 7, num*2))
print ('{} x {} = {}'.format(num, 8, num*2))
print ('{} x {} = {}'.format(num, 9, num*2))
print ('{} x {} = {}'.format(num, 10, num*2))
print('-'*12)